services:
  drone:
    container_name: drone
    environment:
    - DRONE_GITHUB_CLIENT_ID=19f38d57234e5878f709
    - DRONE_GITHUB_CLIENT_SECRET=fc8c19fbdb28cc5750e0cc376013310e6bc454df
    - DRONE_RPC_SECRET=sccba
    - DRONE_SERVER_HOST=122.114.0.26:7080
    - DRONE_SERVER_PROTO=http
    - DRONE_DATABASE_DRIVER=mysql
    - DRONE_DATABASE_DATASOURCE=root:Aa0123@tcp(mysql:3306)/drone?parseTime=true
    image: drone/drone:1
    ports:
    - 7080:80
    - 7443:443
  drone-runner:
    container_name: drone_runner
    environment:
    - DRONE_RPC_PROTO=http
    - DRONE_RPC_HOST=drone:80
    - DRONE_RPC_SECRET=sccba
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_RUNNER_NAME=drone-runner
    image: drone/drone-runner-docker:1
    ports:
    - 3000:3000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gin-admin:
    container_name: gin-admin
    image: test
    ports:
    - 6080:80
    - 8888:8888
    volumes:
    - /home/data/gin-admin/config.yaml:/app/config.yaml
    - /home/data/gin-admin/images:/app/images
    - /home/data/gin-admin/html/:/var/www/
  javabackend:
    command: java -jar /app/origin.jar --spring.datasource.url=jdbc:mysql://mysql:3306/qmplus?useOldAliasMetadataBehavior=true
    container_name: javaBackend
    image: test
    ports:
    - 9081:8080
    volumes:
    - /root/origin/origin/target/:/app/
  minio:
    command: server /data
    container_name: minio
    environment:
    - MINIO_ACCESS_KEY=admin
    - MINIO_SECRET_KEY=Aa012345678
    image: minio/minio
    ports:
    - 9000:9000
    volumes:
    - /home/data/minio:/data
    - /home/data/minio/config:/root/.minio
  mysql:
    container_name: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=Aa0123
    image: mysql:5.7
    ports:
    - 3306:3306
    volumes:
    - /home/data/mysql:/var/lib/mysql
  nginx:
    container_name: wechatFrontNginx
    image: nginx
    ports:
    - 8090:80
    volumes:
    - /home/data/gin-admin/weindex/nginx.conf:/etc/nginx/nginx.conf
version: "3.0"
